#!/usr/bin/perl
#
#removed the paging because you 
#wont want more than 500 results ever
#in mutt
#
# Based on Glenn's AD searcher galore

use warnings;
use strict;
use Net::LDAPS;
use Net::LDAP::Control::Paged;
use Net::LDAP::Constant qw( LDAP_CONTROL_PAGED );

unless(@ARGV) {
	print "No search phrase given\n";
	exit(1);
}

my $search = shift;
my $binduser = '_ldap@olympus.f5net.com';
my $pass = '<Tlnt>N0tG0od';
my $server = 'ad-ldap.olympus.f5net.com';
my $searchbase = 'DC=olympus,DC=F5Net,DC=com';

my $ldaps = Net::LDAPS->new($server, verify => 'none') or die "$!";

my $mesg = $ldaps->bind( $binduser, password=>$pass);
die $mesg->error if $mesg->code;

my $filter = "(&(|(cn=*$search*) (rdn=*$search*) (uid=*$search*) (mail=*$search*))(mail=*))";
my $attrs = "['mail','cn']";

my $results = $ldaps->search( base=>$searchbase, filter=>$filter, attrs=>$attrs);

if($results->count == 0) {
	print "No results matched your search query\n";
	exit(1);
} else {
	print $results->count . " Matching Results\n";
}

for my $entry ($results->entries) {
	if(defined($entry->get_value('mail')) && defined($entry->get_value('cn'))) {
		print $entry->get_value('mail') . "\t" . $entry->get_value('cn') . "\n";
	}
}

$ldaps->unbind;
